runtime: nodejs
vm: true

env_variables:
  # --REQUIRED--
  DATABASE_URI: mongodb://letthemtrust:lttadmin19@ds159574.mlab.com:59574/ltt
  APP_ID: parse-ltt-app-ID
  MASTER_KEY: parse-ltt-master-KEY
  # --OPTIONAL--
  # FILE_KEY: <your-file-key>
  # PARSE_MOUNT: /parse
  # CLOUD_CODE_MAIN:
